import logoblack from "/images/logo-black.png";
import logowhite from "/images/logo-white.png";
import hero from "/images/hero-img.png";
import coffee from "/images/coffee-img.png";
import lalibela from "/images/lalibela.png";
import semien from "/images/semien.png";
import cuisine from "/images/cuisine.png";
import avatar from "/images/avatar.png";
import avatar2 from "/images/avatar2.png";
import gondar from "/images/gondar.png";
import addis from "/images/addisababa.png";
import star from "/images/Star.png";
import image from "/images/image.png";
import lock from "/images/lock.png";
import lighting from "/images/lighting.png";
import folder from "/images/folder.png";

export const logoblackImg = logoblack;
export const logowhiteImg = logowhite;
export const heroImg = hero;
export const coffeeImg = coffee;
export const lalibelaImg = lalibela;
export const semienImg = semien;
export const cuisineImg = cuisine;
export const avatarImg = avatar;
export const avatar2Img = avatar2;
export const gondarImg = gondar;
export const addisImg = addis;
export const starImg = star;
export const imageImg = image;
export const lockImg = lock;
export const lightingImg = lighting;
export const folderImg = folder;
